---
use_hipchat: False
db_dir: /var/log/hooker/db.json
pets:
  key: chupacabra
  branches: 
    master:
      name: master
      docroot: /var/www/pets

    release:
      name: release
      docroot: /var/www/www-pets